---
abstract: unknown
author:
  - 'Athanasios Garyfalos <garyfalos@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Fatal: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Unicode-Peek
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.013002'
resources: {}
version: '0.08'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
